using NUnit.Framework;
using RomanNumerals.Engine;

namespace RomanNumerals.Test.Engine
{
    [TestFixture]
    class SimpleEngineTest
    {
        private SimpleEngine _engine;

        [SetUp]
        public void SetUp()
        {
            _engine = new SimpleEngine();
        }

        [TearDown]
        public void TearDown()
        {
            _engine = null;
        }


        [Test]
        [TestCase('I', 0, "")]
        [TestCase('I', 1, "I")]
        [TestCase('I', 10, "IIIIIIIIII")]
        public void TestRepeatOneChar(char value, int times, string expected)
        {
            var actual = _engine.Repeat(value, times);

            Assert.That(actual, Is.EqualTo(expected));
        }

        [Test]
        #region TestCase
        [TestCase("", 0)]
        [TestCase("I", 1)]
        [TestCase("III", 3)]
        [TestCase("IV", 4)]
        [TestCase("V", 5)]
        [TestCase("VI", 6)]
        [TestCase("VII", 7)]
        [TestCase("VIII", 8)]
        [TestCase("IX", 9)]
        [TestCase("X", 10)]
        [TestCase("XI", 11)]
        [TestCase("XII", 12)]
        [TestCase("XIII", 13)]
        [TestCase("XIV", 14)]
        [TestCase("XV", 15)]
        [TestCase("XVI", 16)]
        [TestCase("XVII", 17)]
        [TestCase("XVIII", 18)]
        [TestCase("XIX", 19)]
        [TestCase("XX", 20)]
        [TestCase("XXI", 21)]
        [TestCase("XXII", 22)]
        [TestCase("XXIII", 23)]
        [TestCase("XXIV", 24)]
        [TestCase("XXV", 25)]
        [TestCase("XXVI", 26)]
        [TestCase("XXVII", 27)]
        [TestCase("XXVIII", 28)]
        [TestCase("XXIX", 29)]
        [TestCase("XXX", 30)]
        [TestCase("XXXI", 31)]
        [TestCase("XXXII", 32)]
        [TestCase("XXXIII", 33)]
        [TestCase("XXXIV", 34)]
        [TestCase("XXXV", 35)]
        [TestCase("XXXVI", 36)]
        [TestCase("XXXVII", 37)]
        [TestCase("XXXVIII", 38)]
        [TestCase("XXXIX", 39)]
        [TestCase("XL", 40)]
        [TestCase("XLI", 41)]
        [TestCase("XLII", 42)]
        [TestCase("XLIII", 43)]
        [TestCase("XLIV", 44)]
        [TestCase("XLV", 45)]
        [TestCase("XLVI", 46)]
        [TestCase("XLVII", 47)]
        [TestCase("XLVIII", 48)]
        [TestCase("XLIX", 49)]
        [TestCase("L", 50)]
        [TestCase("LI", 51)]
        [TestCase("LII", 52)]
        [TestCase("LIII", 53)]
        [TestCase("LIV", 54)]
        [TestCase("LV", 55)]
        [TestCase("LVI", 56)]
        [TestCase("LVII", 57)]
        [TestCase("LVIII", 58)]
        [TestCase("LIX", 59)]
        [TestCase("LX", 60)]
        [TestCase("LXI", 61)]
        [TestCase("LXII", 62)]
        [TestCase("LXIII", 63)]
        [TestCase("LXIV", 64)]
        [TestCase("LXV", 65)]
        [TestCase("LXVI", 66)]
        [TestCase("LXVII", 67)]
        [TestCase("LXVIII", 68)]
        [TestCase("LXIX", 69)]
        [TestCase("LXX", 70)]
        [TestCase("LXXI", 71)]
        [TestCase("LXXII", 72)]
        [TestCase("LXXIII", 73)]
        [TestCase("LXXIV", 74)]
        [TestCase("LXXV", 75)]
        [TestCase("LXXVI", 76)]
        [TestCase("LXXVII", 77)]
        [TestCase("LXXVIII", 78)]
        [TestCase("LXXIX", 79)]
        [TestCase("LXXX", 80)]
        [TestCase("LXXXI", 81)]
        [TestCase("LXXXII", 82)]
        [TestCase("LXXXIII", 83)]
        [TestCase("LXXXIV", 84)]
        [TestCase("LXXXV", 85)]
        [TestCase("LXXXVI", 86)]
        [TestCase("LXXXVII", 87)]
        [TestCase("LXXXVIII", 88)]
        [TestCase("LXXXIX", 89)]
        [TestCase("XC", 90)]
        [TestCase("XCI", 91)]
        [TestCase("XCII", 92)]
        [TestCase("XCIII", 93)]
        [TestCase("XCIV", 94)]
        [TestCase("XCV", 95)]
        [TestCase("XCVI", 96)]
        [TestCase("XCVII", 97)]
        [TestCase("XCVIII", 98)]
        [TestCase("XCIX", 99)]
        [TestCase("C", 100)]
        [TestCase("CX", 110)]
        [TestCase("CXX", 120)]
        [TestCase("CXXX", 130)]
        [TestCase("CXL", 140)]
        [TestCase("CL", 150)]
        [TestCase("CLX", 160)]
        [TestCase("CLXX", 170)]
        [TestCase("CLXXX", 180)]
        [TestCase("CXC", 190)]
        [TestCase("CC", 200)]
        [TestCase("CCX", 210)]
        [TestCase("CCXX", 220)]
        [TestCase("CCXXX", 230)]
        [TestCase("CCXL", 240)]
        [TestCase("CCL", 250)]
        [TestCase("CCLX", 260)]
        [TestCase("CCLXX", 270)]
        [TestCase("CCLXXX", 280)]
        [TestCase("CCXC", 290)]
        [TestCase("CCC", 300)]
        [TestCase("CCCX", 310)]
        [TestCase("CCCXX", 320)]
        [TestCase("CCCXXX", 330)]
        [TestCase("CCCXL", 340)]
        [TestCase("CCCL", 350)]
        [TestCase("CCCLX", 360)]
        [TestCase("CCCLXX", 370)]
        [TestCase("CCCLXXX", 380)]
        [TestCase("CCCXC", 390)]
        [TestCase("CD", 400)]
        [TestCase("CDX", 410)]
        [TestCase("CDXX", 420)]
        [TestCase("CDXXX", 430)]
        [TestCase("CDXL", 440)]
        [TestCase("CDL", 450)]
        [TestCase("CDLX", 460)]
        [TestCase("CDLXX", 470)]
        [TestCase("CDLXXX", 480)]
        [TestCase("CDXC", 490)]
        [TestCase("D", 500)]
        [TestCase("DX", 510)]
        [TestCase("DXX", 520)]
        [TestCase("DXXX", 530)]
        [TestCase("DXL", 540)]
        [TestCase("DL", 550)]
        [TestCase("DLX", 560)]
        [TestCase("DLXX", 570)]
        [TestCase("DLXXX", 580)]
        [TestCase("DXC", 590)]
        [TestCase("DC", 600)]
        [TestCase("DCX", 610)]
        [TestCase("DCXX", 620)]
        [TestCase("DCXXX", 630)]
        [TestCase("DCXL", 640)]
        [TestCase("DCL", 650)]
        [TestCase("DCLX", 660)]
        [TestCase("DCLXX", 670)]
        [TestCase("DCLXXX", 680)]
        [TestCase("DCXC", 690)]
        [TestCase("DCC", 700)]
        [TestCase("DCCX", 710)]
        [TestCase("DCCXX", 720)]
        [TestCase("DCCXXX", 730)]
        [TestCase("DCCXL", 740)]
        [TestCase("DCCL", 750)]
        [TestCase("DCCLX", 760)]
        [TestCase("DCCLXX", 770)]
        [TestCase("DCCLXXX", 780)]
        [TestCase("DCCXC", 790)]
        [TestCase("DCCC", 800)]
        [TestCase("DCCCX", 810)]
        [TestCase("DCCCXX", 820)]
        [TestCase("DCCCXXX", 830)]
        [TestCase("DCCCXL", 840)]
        [TestCase("DCCCL", 850)]
        [TestCase("DCCCLX", 860)]
        [TestCase("DCCCLXX", 870)]
        [TestCase("DCCCLXXX", 880)]
        [TestCase("DCCCLXXXI", 881)]
        [TestCase("DCCCLXXXII", 882)]
        [TestCase("DCCCLXXXIII", 883)]
        [TestCase("DCCCLXXXIV", 884)]
        [TestCase("DCCCLXXXV", 885)]
        [TestCase("DCCCLXXXVI", 886)]
        [TestCase("DCCCLXXXVII", 887)]
        [TestCase("DCCCLXXXVIII", 888)]
        [TestCase("DCCCLXXXIX", 889)]
        [TestCase("DCCCXC", 890)]
        [TestCase("CM", 900)]
        [TestCase("CMX", 910)]
        [TestCase("CMXX", 920)]
        [TestCase("CMXXX", 930)]
        [TestCase("CMXL", 940)]
        [TestCase("CML", 950)]
        [TestCase("CMLX", 960)]
        [TestCase("CMLXX", 970)]
        [TestCase("CMLXXX", 980)]
        [TestCase("CMXC", 990)]
        [TestCase("M", 1000)]
        [TestCase("MC", 1100)]
        [TestCase("MCC", 1200)]
        [TestCase("MCCC", 1300)]
        [TestCase("MCD", 1400)]
        [TestCase("MD", 1500)]
        [TestCase("MDC", 1600)]
        [TestCase("MDCC", 1700)]
        [TestCase("MDCCC", 1800)]
        [TestCase("MCM", 1900)]
        [TestCase("MCMX", 1910)]
        [TestCase("MCMXX", 1920)]
        [TestCase("MCMXXX", 1930)]
        [TestCase("MCMXL", 1940)]
        [TestCase("MCML", 1950)]
        [TestCase("MCMLX", 1960)]
        [TestCase("MCMLXX", 1970)]
        [TestCase("MCMLXXX", 1980)]
        [TestCase("MCMLXXXI", 1981)]
        [TestCase("MCMLXXXII", 1982)]
        [TestCase("MCMLXXXIII", 1983)]
        [TestCase("MCMLXXXIV", 1984)]
        [TestCase("MCMLXXXV", 1985)]
        [TestCase("MCMLXXXVI", 1986)]
        [TestCase("MCMLXXXVII", 1987)]
        [TestCase("MCMLXXXVIII", 1988)]
        [TestCase("MCMLXXXIX", 1989)]
        [TestCase("MCMXC", 1990)]
        [TestCase("MM", 2000)]
        [TestCase("MMM", 3000)]
        [TestCase("MMMCMXC", 3990)]
        [TestCase("MMMCMXCI", 3991)]
        [TestCase("MMMCMXCII", 3992)]
        [TestCase("MMMCMXCIII", 3993)]
        [TestCase("MMMCMXCIV", 3994)]
        [TestCase("MMMCMXCV", 3995)]
        [TestCase("MMMCMXCVI", 3996)]
        [TestCase("MMMCMXCVII", 3997)]
        [TestCase("MMMCMXCVIII", 3998)]
        [TestCase("MMMCMXCIX", 3999)]
        #endregion
        public void TestMapFromRomanNormalToRomanOnes(string roman, int times)
        {
            var actual = _engine.ToRomanOnes(roman);
            var expected = _engine.Repeat('I', times);

            Assert.That(actual, Is.EqualTo(expected));
        }

        [Test]
        #region
        [TestCase("")]
        [TestCase("I")]
        [TestCase("III")]
        [TestCase("IV")]
        [TestCase("V")]
        [TestCase("VI")]
        [TestCase("VII")]
        [TestCase("VIII")]
        [TestCase("IX")]
        [TestCase("X")]
        [TestCase("XI")]
        [TestCase("XII")]
        [TestCase("XIII")]
        [TestCase("XIV")]
        [TestCase("XV")]
        [TestCase("XVI")]
        [TestCase("XVII")]
        [TestCase("XVIII")]
        [TestCase("XIX")]
        [TestCase("XX")]
        [TestCase("XXI")]
        [TestCase("XXII")]
        [TestCase("XXIII")]
        [TestCase("XXIV")]
        [TestCase("XXV")]
        [TestCase("XXVI")]
        [TestCase("XXVII")]
        [TestCase("XXVIII")]
        [TestCase("XXIX")]
        [TestCase("XXX")]
        [TestCase("XXXI")]
        [TestCase("XXXII")]
        [TestCase("XXXIII")]
        [TestCase("XXXIV")]
        [TestCase("XXXV")]
        [TestCase("XXXVI")]
        [TestCase("XXXVII")]
        [TestCase("XXXVIII")]
        [TestCase("XXXIX")]
        [TestCase("XL")]
        [TestCase("XLI")]
        [TestCase("XLII")]
        [TestCase("XLIII")]
        [TestCase("XLIV")]
        [TestCase("XLV")]
        [TestCase("XLVI")]
        [TestCase("XLVII")]
        [TestCase("XLVIII")]
        [TestCase("XLIX")]
        [TestCase("L")]
        [TestCase("LI")]
        [TestCase("LII")]
        [TestCase("LIII")]
        [TestCase("LIV")]
        [TestCase("LV")]
        [TestCase("LVI")]
        [TestCase("LVII")]
        [TestCase("LVIII")]
        [TestCase("LIX")]
        [TestCase("LX")]
        [TestCase("LXI")]
        [TestCase("LXII")]
        [TestCase("LXIII")]
        [TestCase("LXIV")]
        [TestCase("LXV")]
        [TestCase("LXVI")]
        [TestCase("LXVII")]
        [TestCase("LXVIII")]
        [TestCase("LXIX")]
        [TestCase("LXX")]
        [TestCase("LXXI")]
        [TestCase("LXXII")]
        [TestCase("LXXIII")]
        [TestCase("LXXIV")]
        [TestCase("LXXV")]
        [TestCase("LXXVI")]
        [TestCase("LXXVII")]
        [TestCase("LXXVIII")]
        [TestCase("LXXIX")]
        [TestCase("LXXX")]
        [TestCase("LXXXI")]
        [TestCase("LXXXII")]
        [TestCase("LXXXIII")]
        [TestCase("LXXXIV")]
        [TestCase("LXXXV")]
        [TestCase("LXXXVI")]
        [TestCase("LXXXVII")]
        [TestCase("LXXXVIII")]
        [TestCase("LXXXIX")]
        [TestCase("XC")]
        [TestCase("XCI")]
        [TestCase("XCII")]
        [TestCase("XCIII")]
        [TestCase("XCIV")]
        [TestCase("XCV")]
        [TestCase("XCVI")]
        [TestCase("XCVII")]
        [TestCase("XCVIII")]
        [TestCase("XCIX")]
        [TestCase("C")]
        [TestCase("CX")]
        [TestCase("CXX")]
        [TestCase("CXXX")]
        [TestCase("CXL")]
        [TestCase("CL")]
        [TestCase("CLX")]
        [TestCase("CLXX")]
        [TestCase("CLXXX")]
        [TestCase("CXC")]
        [TestCase("CC")]
        [TestCase("CCX")]
        [TestCase("CCXX")]
        [TestCase("CCXXX")]
        [TestCase("CCXL")]
        [TestCase("CCL")]
        [TestCase("CCLX")]
        [TestCase("CCLXX")]
        [TestCase("CCLXXX")]
        [TestCase("CCXC")]
        [TestCase("CCC")]
        [TestCase("CCCX")]
        [TestCase("CCCXX")]
        [TestCase("CCCXXX")]
        [TestCase("CCCXL")]
        [TestCase("CCCL")]
        [TestCase("CCCLX")]
        [TestCase("CCCLXX")]
        [TestCase("CCCLXXX")]
        [TestCase("CCCXC")]
        [TestCase("CD")]
        [TestCase("CDX")]
        [TestCase("CDXX")]
        [TestCase("CDXXX")]
        [TestCase("CDXL")]
        [TestCase("CDL")]
        [TestCase("CDLX")]
        [TestCase("CDLXX")]
        [TestCase("CDLXXX")]
        [TestCase("CDXC")]
        [TestCase("D")]
        [TestCase("DX")]
        [TestCase("DXX")]
        [TestCase("DXXX")]
        [TestCase("DXL")]
        [TestCase("DL")]
        [TestCase("DLX")]
        [TestCase("DLXX")]
        [TestCase("DLXXX")]
        [TestCase("DXC")]
        [TestCase("DC")]
        [TestCase("DCX")]
        [TestCase("DCXX")]
        [TestCase("DCXXX")]
        [TestCase("DCXL")]
        [TestCase("DCL")]
        [TestCase("DCLX")]
        [TestCase("DCLXX")]
        [TestCase("DCLXXX")]
        [TestCase("DCXC")]
        [TestCase("DCC")]
        [TestCase("DCCX")]
        [TestCase("DCCXX")]
        [TestCase("DCCXXX")]
        [TestCase("DCCXL")]
        [TestCase("DCCL")]
        [TestCase("DCCLX")]
        [TestCase("DCCLXX")]
        [TestCase("DCCLXXX")]
        [TestCase("DCCXC")]
        [TestCase("DCCC")]
        [TestCase("DCCCX")]
        [TestCase("DCCCXX")]
        [TestCase("DCCCXXX")]
        [TestCase("DCCCXL")]
        [TestCase("DCCCL")]
        [TestCase("DCCCLX")]
        [TestCase("DCCCLXX")]
        [TestCase("DCCCLXXX")]
        [TestCase("DCCCLXXXI")]
        [TestCase("DCCCLXXXII")]
        [TestCase("DCCCLXXXIII")]
        [TestCase("DCCCLXXXIV")]
        [TestCase("DCCCLXXXV")]
        [TestCase("DCCCLXXXVI")]
        [TestCase("DCCCLXXXVII")]
        [TestCase("DCCCLXXXVIII")]
        [TestCase("DCCCLXXXIX")]
        [TestCase("DCCCXC")]
        [TestCase("CM")]
        [TestCase("CMX")]
        [TestCase("CMXX")]
        [TestCase("CMXXX")]
        [TestCase("CMXL")]
        [TestCase("CML")]
        [TestCase("CMLX")]
        [TestCase("CMLXX")]
        [TestCase("CMLXXX")]
        [TestCase("CMXC")]
        [TestCase("M")]
        [TestCase("MC")]
        [TestCase("MCC")]
        [TestCase("MCCC")]
        [TestCase("MCD")]
        [TestCase("MD")]
        [TestCase("MDC")]
        [TestCase("MDCC")]
        [TestCase("MDCCC")]
        [TestCase("MCM")]
        [TestCase("MCMX")]
        [TestCase("MCMXX")]
        [TestCase("MCMXXX")]
        [TestCase("MCMXL")]
        [TestCase("MCML")]
        [TestCase("MCMLX")]
        [TestCase("MCMLXX")]
        [TestCase("MCMLXXX")]
        [TestCase("MCMLXXXI")]
        [TestCase("MCMLXXXII")]
        [TestCase("MCMLXXXIII")]
        [TestCase("MCMLXXXIV")]
        [TestCase("MCMLXXXV")]
        [TestCase("MCMLXXXVI")]
        [TestCase("MCMLXXXVII")]
        [TestCase("MCMLXXXVIII")]
        [TestCase("MCMLXXXIX")]
        [TestCase("MCMXC")]
        [TestCase("MM")]
        [TestCase("MMM")]
        [TestCase("MMMCMXC")]
        [TestCase("MMMCMXCI")]
        [TestCase("MMMCMXCII")]
        [TestCase("MMMCMXCIII")]
        [TestCase("MMMCMXCIV")]
        [TestCase("MMMCMXCV")]
        [TestCase("MMMCMXCVI")]
        [TestCase("MMMCMXCVII")]
        [TestCase("MMMCMXCVIII")]
        [TestCase("MMMCMXCIX")]
        #endregion
        public void TestMapToRomanOnesAndReturnRomanNormalResultShouldBeEquals(string roman)
        {
            var romanOnes = _engine.ToRomanOnes(roman);
            var actual = _engine.ToRomanNormal(romanOnes);

            Assert.That(actual, Is.EqualTo(roman));
        }
    }
}